### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Ankiewicz** [danielbayley/atom-modular-snippets#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [modular-snippets](https://github.com/danielbayley/atom-modular-snippets) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

TypeError: Cannot read property 'startsWith' of undefined
    at /Users/jankiewicz/.atom/packages/modular-snippets/index.coffee:49:22
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:666:26)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:742:16)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:726:21)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:23.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-jshint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10
atom-bootstrap4, v1.4.0
emmet, v2.4.3
highlight-selected, v0.11.2
jade-beautify, v0.1.5
javascript-snippets, v1.2.1
language-ejs, v0.2.0
language-pug, v0.0.17
linter, v1.11.14
linter-eslint, v7.2.4
linter-htmlhint, v1.3.0
linter-scss-lint, v3.0.4
modular-snippets, v0.1.2
personal-snippets, vundefined
pigments, v0.31.2
pretty-json, v1.4.4
react, v0.15.0
standard-formatter, v2.0.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by danielbayley** [comment]
> personal-snippets, vundefined

@Ankiewicz I wonder if this might have anything to do with it?

**Comment by Ankiewicz** [comment]
Thank you, I deleted the folder from packages and it works without throwing an error. This was my attempting to load the snippets without your package.

THANK YOU!!

**Comment by danielbayley** [comment]
@Ankiewicz So that _was_ the cause or not? This package loads your snippets from `ATOM_HOME/snippets` so just move them into there…

**Comment by Ankiewicz** [comment]
Yes it appears to have been.

**Comment by Ankiewicz** [comment]
Okay, as soon as I said yes, it showed up again, of course

**Comment by Ankiewicz** [comment]
<img width="516" alt="screen shot 2016-08-02 at 9 32 50 am" src="https://cloud.githubusercontent.com/assets/11892928/17336701/328315f6-5894-11e6-8be9-199fafac137b.png">
<img width="511" alt="screen shot 2016-08-02 at 9 33 10 am" src="https://cloud.githubusercontent.com/assets/11892928/17336700/32825bac-5894-11e6-9664-62deb105cba2.png">

Not sure if these help at all. Please let me know if there is anything else I can do to help resolve the bug. 

Could it be two different packages conflicting?

**Comment by danielbayley** [comment]
> Okay, as soon as I said yes, it showed up again, of course

Always the way… 😄

@Ankiewicz Just looking at this… Iv’e actually refactored the code a bit since the last update on my local copy so will push an update that should/might correct this (it makes heavier use of the `?` existential operator…)

> Could it be two different packages conflicting?

I don’t think so, but do you still have that _personal-snippets_ package running?

The error is thrown from [this line](https://github.com/danielbayley/atom-modular-snippets/blob/master/index.coffee#L49) so it’s not picking up `@project` (which is just `atom.project.getPaths()[0]`), not sure why… Is it actually loading your snippets from `ATOM_HOME/snippets` and/or you local project snippets?

**Comment by Ankiewicz** [comment]
> I don’t think so, but do you still have that personal-snippets package running?
> No I deleted the folder. I am still using the snippets, but that attempt of creating my own package, I dropped it. 

I created a folder "snippets" in the atom file and it's working from there.(attached image of folder structure)
<img width="639" alt="screen shot 2016-08-08 at 12 46 56 pm" src="https://cloud.githubusercontent.com/assets/11892928/17493680/448f6174-5d66-11e6-9c88-b8921ccf71fd.png">

**Comment by Ankiewicz** [comment]
also, wanted to note it only occurs when I save the file.

**Comment by guerrero** [comment]
Same problem here, these are the steps I followed to reproduce the bug:
1. Open folder in Atom
2. Create new folder
3. Create new file using _Application: New File_ command
4. Save it in the new folder I've created before

After the step number 4 the error shows up. It seems that path is undefined for files created using _Application: New File_ and it produces that `startsWith` can be reached because `path` is undefined. A simple workaround could be check if path exists before execute that part of the code.

**Comment by cristianPerez** [comment]
This is the best config. 
https://gist.github.com/radiovisual/7c27e5a1d0f7aa56e0e3922c98e19ffc
